name: Deploy Dockerized Node App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      MYSQL_USER: ${{ secrets.DOCUHUB_DB_USER }}
      MYSQL_PASSWORD: ${{ secrets.DOCUHUB_DB_PASS }}
      MYSQL_DB: docuHub_k8s_documents_service
      MYSQL_HOSTNAME: ${{ secrets.DOCUHUB_DB_HOST }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set dynamic DATABASE_URL
      run: |
        echo "DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_HOSTNAME/$MYSQL_DB" >> $GITHUB_ENV

    - name: Create .env for container
      run: |
        echo "DATABASE_URL=${{ env.DATABASE_URL }}" > .env

    - name: Build Docker image
      run: docker build -t docuhub-app .

    - name: Stop container using port 3000 (if any)
      run: |
        CONTAINER_ID=$(docker ps -q --filter "publish=3000")
        if [ -n "$CONTAINER_ID" ]; then
          echo "Stopping container using port 3000..."
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID
        fi

    - name: Remove old container (if named docuhub)
      run: docker rm -f docuhub || true

    - name: Run Docker container
      run: |
        docker run -d \
          --name docuhub \
          -p 3000:3000 \
          --env-file .env \
          docuhub-app
